spring:
  profiles:
    active: local # 기본 환경 선택

management:
  security:
    enabled=false:
# local 환경
---
spring:
#  profiles: local
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path : /h2-console
  hibernate:
    ddl-auto=update:
